package com.myspace.person;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String firstName;
	private java.lang.String lastName;
	private java.lang.Integer age;
	private java.lang.Integer empId;
	private java.lang.Integer salary;

	private java.util.List<com.myspace.person.Address> locations;

	public Person() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(java.lang.Integer empId) {
		this.empId = empId;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public java.util.List<com.myspace.person.Address> getLocations() {
		return this.locations;
	}

	public void setLocations(
			java.util.List<com.myspace.person.Address> locations) {
		this.locations = locations;
	}

	public Person(java.lang.String firstName, java.lang.String lastName,
			java.lang.Integer age, java.lang.Integer empId,
			java.lang.Integer salary,
			java.util.List<com.myspace.person.Address> locations) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.age = age;
		this.empId = empId;
		this.salary = salary;
		this.locations = locations;
	}

}