package com.myspace.trainstation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Train implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String departureStation;
	private java.lang.String destinationStation;
	private Integer railNumber;

	public Train() {
	}

	public java.lang.String getDepartureStation() {
		return this.departureStation;
	}

	public void setDepartureStation(java.lang.String departureStation) {
		this.departureStation = departureStation;
	}

	public java.lang.String getDestinationStation() {
		return this.destinationStation;
	}

	public void setDestinationStation(java.lang.String destinationStation) {
		this.destinationStation = destinationStation;
	}

	public java.lang.Integer getRailNumber() {
		return this.railNumber;
	}

	public void setRailNumber(java.lang.Integer railNumber) {
		this.railNumber = railNumber;
	}

	public Train(java.lang.String departureStation,
			java.lang.String destinationStation, java.lang.Integer railNumber) {
		this.departureStation = departureStation;
		this.destinationStation = destinationStation;
		this.railNumber = railNumber;
	}

}